# meta
listen_host: "127.0.0.1"
port: 50048
data_dir: "build/runtime/data/meta"

# sdm
sdm_host: "127.0.0.1"
sdm_port: 50049

# log
logger_name: "meta_log"
log_dir: "build/runtime/logs/meta"
log_filename: "meta.log"
log_level: "debug"
log_to_console: false
log_to_file: true
