listen_host: "127.0.0.1"
port: 50048
sdm_host: "127.0.0.1"
sdm_port: 50049
data_dir: "./build/data/meta"

logger_name: "meta_log"
log_dir: "./build/logs/meta"
log_filename: "meta.log"
log_level: "debug"
log_to_console: true
log_to_file: true